spring:
  velocity:
    suffix: .vm
    check-template-location: true
    properties:
      resource:
        loader: spring
    spring:
      loader:
        class: org.springframework.ui.velocity.SpringResourceLoader
        cache: true
